[package]
name = "dir-scanner"
version = "0.1.0"
authors = ["ludwig <ludwig.beckert@outlook.de>"]
edition = "2018"

[dependencies]
structopt = "0.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
error-chain = "0.12.4"

